package main

import (
	"context"
	"testing"
	"text/template"
	"time"

	"github.com/Masterminds/sprig/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// mockClientWithCapture extends mockClient to capture UpdateDocuments args.
type mockClientWithCapture struct {
	*mockClient
	lastSuggestions []DocumentSuggestion
}

func (m *mockClientWithCapture) UpdateDocuments(ctx context.Context, documents []DocumentSuggestion, db *gorm.DB, isUndo bool) error {
	m.updateDocsCalled = true
	m.lastSuggestions = documents
	return nil
}

func TestClassifyDocument_Exists(t *testing.T) {
	origAutoTag, origAutoOcrTag := autoTag, autoOcrTag
	t.Cleanup(func() {
		autoTag = origAutoTag
		autoOcrTag = origAutoOcrTag
	})
	autoTag = "paperless-gpt-auto"
	autoOcrTag = "paperless-gpt-ocr-auto"

	origTitle := autoGenerateTitle
	origTags := autoGenerateTags
	origCorr := autoGenerateCorrespondents
	origDate := autoGenerateCreatedDate
	origDocType := autoGenerateDocumentType
	autoGenerateTitle = "false"
	autoGenerateTags = "false"
	autoGenerateCorrespondents = "false"
	autoGenerateCreatedDate = "false"
	autoGenerateDocumentType = "false"
	t.Cleanup(func() {
		autoGenerateTitle = origTitle
		autoGenerateTags = origTags
		autoGenerateCorrespondents = origCorr
		autoGenerateCreatedDate = origDate
		autoGenerateDocumentType = origDocType
	})

	env := setupTest(t)
	defer env.teardown()

	setupTestCase(&OCRTestCase{documents: []TestDocument{}}, env)

	client := newMockClient(env.client)
	app := &App{
		Client:   client,
		Database: env.db,
	}

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "OCR text about an electric bill",
		Tags:    []string{autoOcrTag},
	}

	suggestion, err := app.classifyDocument(context.Background(), doc, documentLogger(doc.ID))
	require.NoError(t, err)
	assert.NotNil(t, suggestion)
	assert.Equal(t, 1, suggestion.ID)
}

func TestProcessAutoOcrTagDocuments_ChainingDisabled(t *testing.T) {
	origAutoOcrTag, origAutoTag, origPdfOCRCompleteTag := autoOcrTag, autoTag, pdfOCRCompleteTag
	origChaining := autoOcrThenClassify
	t.Cleanup(func() {
		autoOcrTag = origAutoOcrTag
		autoTag = origAutoTag
		pdfOCRCompleteTag = origPdfOCRCompleteTag
		autoOcrThenClassify = origChaining
	})
	autoOcrTag = "paperless-gpt-ocr-auto"
	autoTag = "paperless-gpt-auto"
	pdfOCRCompleteTag = "paperless-gpt-ocr-complete"
	autoOcrThenClassify = false

	env := setupTest(t)
	defer env.teardown()

	ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()

	base := newMockClient(env.client)
	client := &mockClientWithCapture{mockClient: base}
	client.AddTag(autoOcrTag, 2)

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "Original tesseract text",
		Tags:    []string{autoOcrTag},
	}
	client.AddDocument(doc, []string{autoOcrTag})

	app := &App{
		Client:         client,
		Database:       env.db,
		ocrProvider:    &mockOCRProvider{text: "Better OCR text"},
		docProcessor:   &mockDocumentProcessor{mockText: "Better OCR text"},
		ocrProcessMode: "image",
	}

	count, err := app.processAutoOcrTagDocuments(ctx)
	require.NoError(t, err)
	assert.Equal(t, 1, count)
	assert.True(t, client.updateDocsCalled)

	require.Len(t, client.lastSuggestions, 1)
	assert.Equal(t, "Better OCR text", client.lastSuggestions[0].SuggestedContent)
	assert.Empty(t, client.lastSuggestions[0].SuggestedTitle)
}

func TestProcessAutoOcrTagDocuments_ChainingEnabled_ClassifySucceeds(t *testing.T) {
	origAutoOcrTag, origAutoTag, origPdfOCRCompleteTag := autoOcrTag, autoTag, pdfOCRCompleteTag
	origChaining := autoOcrThenClassify
	origOCRTemplate := ocrTemplate
	origTitle := autoGenerateTitle
	origTags := autoGenerateTags
	origCorr := autoGenerateCorrespondents
	origDate := autoGenerateCreatedDate
	origDocType := autoGenerateDocumentType
	t.Cleanup(func() {
		autoOcrTag = origAutoOcrTag
		autoTag = origAutoTag
		pdfOCRCompleteTag = origPdfOCRCompleteTag
		autoOcrThenClassify = origChaining
		ocrTemplate = origOCRTemplate
		autoGenerateTitle = origTitle
		autoGenerateTags = origTags
		autoGenerateCorrespondents = origCorr
		autoGenerateCreatedDate = origDate
		autoGenerateDocumentType = origDocType
	})

	autoOcrTag = "paperless-gpt-ocr-auto"
	autoTag = "paperless-gpt-auto"
	pdfOCRCompleteTag = "paperless-gpt-ocr-complete"

	var err error
	ocrTemplate, err = template.New("ocr").Funcs(sprig.FuncMap()).Parse("OCR prompt")
	require.NoError(t, err)

	autoOcrThenClassify = true
	autoGenerateTitle = "false"
	autoGenerateTags = "false"
	autoGenerateCorrespondents = "false"
	autoGenerateCreatedDate = "false"
	autoGenerateDocumentType = "false"

	env := setupTest(t)
	defer env.teardown()

	setupTestCase(&OCRTestCase{
		documents: []TestDocument{
			{ID: 1, Title: "Test Doc", Tags: []string{autoOcrTag}},
		},
	}, env)

	ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
	defer cancel()

	base := newMockClient(env.client)
	client := &mockClientWithCapture{mockClient: base}
	client.AddTag(autoOcrTag, 2)
	client.AddTag(autoTag, 1)

	doc := Document{
		ID:      1,
		Title:   "Test Doc",
		Content: "Original tesseract text",
		Tags:    []string{autoOcrTag},
	}
	client.AddDocument(doc, []string{autoOcrTag})

	app := &App{
		Client:            client,
		Database:          env.db,
		ocrProvider:       &mockOCRProvider{text: "Better OCR text"},
		docProcessor:      &mockDocumentProcessor{mockText: "Better OCR text"},
		ocrProcessMode:    "image",
		pdfOCRTagging:     true,
		pdfOCRCompleteTag: pdfOCRCompleteTag,
	}

	count, err := app.processAutoOcrTagDocuments(ctx)
	require.NoError(t, err)
	assert.Equal(t, 1, count)
	assert.True(t, client.updateDocsCalled)

	require.Len(t, client.lastSuggestions, 1)
	assert.Equal(t, "Better OCR text", client.lastSuggestions[0].SuggestedContent)
	assert.Contains(t, client.lastSuggestions[0].RemoveTags, autoTag)
	assert.Contains(t, client.lastSuggestions[0].RemoveTags, autoOcrTag)
	assert.Contains(t, client.lastSuggestions[0].SuggestedTags, pdfOCRCompleteTag)
}
